import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/page_acceuil/Home.module.scss'
import Navbar from '../components/Navbar'
import SectionAcceuil from '../components/page_acceuil/SectionAcceuil'
import SectionContreparti from '../components/page_acceuil/SectionContreparti'
import Sensibilisation from '../components/page_acceuil/Sensibilisation'
import SectionNotreParticipation from '../components/page_acceuil/SectionNotreParticipation'
import FaireUnDon from '../components/page_acceuil/FaireUnDon'
import SectionSante from '../components/page_acceuil/SectionSante'
import SectionValorisationDeDechets from '../components/page_acceuil/SectionValorisationDeDechets'
import SectionNosPartenaires from '../components/page_acceuil/SectionNosPartenaires'
import Footer from '../components/Footer'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Benelux Afro Center</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar />
      
      <main className={styles.main}>
        <SectionAcceuil />
        <SectionContreparti />
        <Sensibilisation />
        <SectionNotreParticipation/>
        <FaireUnDon />
        <SectionSante />
        <SectionValorisationDeDechets />
        <SectionNosPartenaires />
        <Footer/>
      </main>

    </div>
  )
}
